# Generated by Django 3.2.6 on 2021-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('adres', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Nazwa',
            },
        ),
    ]
