# Generated by Django 3.2.6 on 2021-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nrDowodu', models.IntegerField(blank=True, null=True)),
                ('jezyk', models.CharField(blank=True, choices=[('EN', 'English'), ('PL', 'Polish')], max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Uczestnik',
            },
        ),
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpPopr', models.CharField(max_length=20)),
                ('odpNiepopr', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Odpowiedz',
            },
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('obraz', models.ImageField(upload_to='')),
                ('jezyk', models.CharField(blank=True, choices=[('EN', 'English'), ('PL', 'Polish')], max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pytanie',
            },
        ),
        migrations.CreateModel(
            name='Szkolenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('obraz', models.ImageField(upload_to='')),
                ('jezyk', models.CharField(blank=True, choices=[('EN', 'English'), ('PL', 'Polish')], max_length=2, null=True)),
                ('gosc', models.ManyToManyField(blank=True, null=True, to='modelszkolenie.Gosc')),
            ],
            options={
                'verbose_name_plural': 'Szkolenie',
            },
        ),
    ]
