# Generated by Django 3.2.6 on 2021-08-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0002_gosc_odpowiedz_pytanie_szkolenie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szkolenie',
            name='gosc',
        ),
    ]
