# Generated by Django 3.2.6 on 2021-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0004_auto_20210804_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='szkolenie',
            name='lista_gosci',
            field=models.ManyToManyField(to='modelszkolenie.Gosc'),
        ),
    ]
