# Generated by Django 3.2.6 on 2021-08-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0006_gosc_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpowiedz',
            name='pytanie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelszkolenie.pytanie'),
        ),
    ]
