# Generated by Django 3.2.6 on 2021-08-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0007_odpowiedz_pytanie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrazDoGalerii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('obraz', models.ImageField(upload_to='images/szkolenie/galeria')),
                ('data', models.DateField()),
            ],
        ),
    ]
