# Generated by Django 3.2.6 on 2021-08-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0008_obrazdogalerii'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrazdogalerii',
            name='szkolenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelszkolenie.szkolenie'),
        ),
    ]
