# Generated by Django 3.2.6 on 2021-08-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0009_obrazdogalerii_szkolenie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrazdogalerii',
            options={'verbose_name_plural': 'Galeria'},
        ),
    ]
