# Generated by Django 3.2.6 on 2021-08-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0010_alter_obrazdogalerii_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name_plural': 'Firma'},
        ),
    ]
