# Generated by Django 3.2.6 on 2021-08-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelszkolenie', '0012_auto_20210805_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='firma_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obrazdogalerii',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
