# Generated by Django 3.2.6 on 2021-08-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0013_auto_20210805_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='firma_poster',
            new_name='firma',
        ),
    ]
