# Generated by Django 3.2.6 on 2021-08-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0014_rename_firma_poster_firma_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='firma',
        ),
        migrations.AlterField(
            model_name='gosc',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelszkolenie.firma'),
        ),
    ]
