# Generated by Django 3.2.6 on 2021-08-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0015_auto_20210805_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gosc',
            name='nrDowodu',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
