# Generated by Django 3.2.6 on 2021-08-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0016_alter_gosc_nrdowodu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gosc',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='szkolenie',
            name='lista_gosci',
        ),
        migrations.AddField(
            model_name='szkolenie',
            name='listCustomers',
            field=models.ManyToManyField(to='modelszkolenie.User'),
        ),
    ]
