# Generated by Django 3.2.6 on 2021-08-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0017_auto_20210805_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Odpowiedz',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Firma',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='ObrazDoGalerii',
            new_name='GaleryImage',
        ),
        migrations.RenameModel(
            old_name='Pytanie',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Szkolenie',
            new_name='Training',
        ),
    ]
