# Generated by Django 3.2.6 on 2021-08-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0018_auto_20210805_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='data',
        ),
        migrations.AddField(
            model_name='training',
            name='koniec',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='poczatek',
            field=models.DateTimeField(null=True),
        ),
    ]
