# Generated by Django 3.2.6 on 2021-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0019_auto_20210805_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='koniec',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='poczatek',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
