# Generated by Django 3.2.6 on 2021-08-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0020_auto_20210805_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='modelszkolenie.company'),
        ),
    ]
