# Generated by Django 3.2.6 on 2021-08-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelszkolenie', '0021_alter_user_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
