# Generated by Django 3.2.6 on 2021-08-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0022_auto_20210805_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
    ]
