# Generated by Django 3.2.6 on 2021-08-05 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0023_auto_20210805_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeryimage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Galeria'},
        ),
        migrations.RenameField(
            model_name='galeryimage',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='odpNiepopr',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='odpPopr',
        ),
        migrations.RemoveField(
            model_name='training',
            name='koniec',
        ),
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='odp',
            field=models.TextField(default=datetime.datetime(2021, 8, 5, 12, 6, 5, 83709, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='pytanie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelszkolenie.question'),
        ),
        migrations.AlterField(
            model_name='galeryimage',
            name='tytul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='nazwa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='poczatek',
            field=models.DateField(blank=True, null=True),
        ),
    ]
