# Generated by Django 3.2.6 on 2021-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0025_alter_training_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='listCustomers',
            field=models.ManyToManyField(blank=True, to='modelszkolenie.User'),
        ),
    ]
