# Generated by Django 3.2.6 on 2021-08-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0029_rename_duration_training_czas'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('obraz', models.ImageField(upload_to='images/szkolenie/galeria')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pytanie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelszkolenie.question')),
            ],
            options={
                'verbose_name_plural': 'Galeria pytan',
                'ordering': ['-date'],
            },
        ),
    ]
