# Generated by Django 3.2.6 on 2021-08-05 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0030_questionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='czas',
            field=models.DurationField(db_column='czas', verbose_name=datetime.timedelta(days=1)),
        ),
    ]
