# Generated by Django 3.2.6 on 2021-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0031_alter_training_czas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='uczestnicy',
            field=models.ManyToManyField(blank=True, to='modelszkolenie.User'),
        ),
    ]
