# Generated by Django 3.2.6 on 2021-08-05 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0032_alter_training_uczestnicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='czas',
            field=models.DurationField(verbose_name=datetime.timedelta(days=1)),
        ),
    ]
