# Generated by Django 3.2.6 on 2021-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0033_alter_training_czas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nrDowodu',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
