# Generated by Django 3.2.6 on 2021-08-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0034_alter_user_nrdowodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='czas',
            field=models.DurationField(verbose_name='czas'),
        ),
    ]
