# Generated by Django 3.2.6 on 2021-08-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0035_alter_training_czas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='jezyk',
            field=models.CharField(blank=True, choices=[('EN', 'Angielski'), ('PL', 'Polski')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='jezyk',
            field=models.CharField(blank=True, choices=[('EN', 'Angielski'), ('PL', 'Polski')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='jezyk',
            field=models.CharField(blank=True, choices=[('EN', 'Angielski'), ('PL', 'Polski')], max_length=2, null=True),
        ),
    ]
