# Generated by Django 3.2.6 on 2021-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0037_remove_question_obraz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='obraz',
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='obraz',
            field=models.ImageField(upload_to='images/pytanie/galeria'),
        ),
    ]
