# Generated by Django 3.2.6 on 2021-08-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0038_auto_20210806_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeryimage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Galeria ze szkolenia'},
        ),
    ]
