# Generated by Django 3.2.6 on 2021-08-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0041_auto_20210806_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtraining',
            options={'verbose_name_plural': 'Ukonczone szkolenia'},
        ),
        migrations.AlterModelOptions(
            name='questionimage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Galeria pytan na szkoleniu'},
        ),
    ]
