# Generated by Django 3.2.6 on 2021-08-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0042_auto_20210806_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryimage',
            name='tytul',
            field=models.CharField(max_length=255, verbose_name='tytuł'),
        ),
    ]
