# Generated by Django 3.2.6 on 2021-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0043_alter_galeryimage_tytul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(default=False, verbose_name='Czy poprawna'),
        ),
    ]
