# Generated by Django 3.2.6 on 2021-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0044_alter_answer_iscorrect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imie',
            field=models.CharField(max_length=30, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nrDowodu',
            field=models.CharField(max_length=26, null=True, verbose_name='Numer dowodu'),
        ),
    ]
