# Generated by Django 3.2.6 on 2021-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0045_auto_20210806_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jezyk',
            field=models.CharField(blank=True, choices=[('EN', 'Angielski'), ('PL', 'Polski')], max_length=2, null=True, verbose_name='Język'),
        ),
    ]
