# Generated by Django 3.2.6 on 2021-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelszkolenie', '0047_auto_20210806_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='uczestnicy',
            field=models.ManyToManyField(blank=True, through='modelszkolenie.CompletedTraining', to='modelszkolenie.User'),
        ),
    ]
